### ISSUE TITLE
Periodically check for changes and sync with S3

### ISSUE THREAD

**Issue by smiller171** [elementar/docker-s3-volume#5]
It seems this could be far more useful if you sync periodically, so that if the host server dies unexpectedly, you have most if not all of the data.

If you sync fast enough you could also use many of these on different nodes to sync data across an auto scaling group

**Comment by fabiob** [comment]
My fork adds periodic sync, and some more changes. Check it out: https://github.com/elementar/docker-s3-volume

@whatupdave, I haven't submitted a PR since my fork is using another repository name for the documentation and Makefile.

**Comment by whatupdave** [comment]
Hey @fabiob I don't really use this any more, if you'd like, I'll transfer the repo to you so you have the canonical version. Is that cool?

**Comment by fabiob** [comment]
Sure, @whatupdave, I would appreciate it :)

**Comment by fabiob** [comment]
The current image now supports periodical sync using the `BACKUP_INTERVAL` environment variable.
