### ISSUE TITLE
softLayer IBM s3

### ISSUE THREAD

**Issue by sarkistlt** [elementar/docker-s3-volume#9]
is it possible to add support for it? only missing env is ENDPOINT

**Comment by fabiob** [comment]
@sarkistlt, can you send a PR for that?

**Comment by fabiob** [comment]
Also, have you tried specifying the environment variable when running the container? It should support any environment variable supported by the `aws-cli` command.

**Comment by sarkistlt** [comment]
let me test a couple things first, I think it will require new s3cfg file for IBM, but it's possible to have 2 conf file, lets say default and `s3cfg-ibm`, then if you want to use IBM all you need is add one more env. variable `AWS_CONFIG_FILE=/s3cfg-ibm`

**Comment by fabiob** [comment]
Closed until OP sends more info.
